Update ecu2pvoutput.py
Version 2.1.2 changed field numbers

Traceback (most recent call last):
  File "ec2pvoutput.py", line 79, in <module>
    avgvoltage = mean(res3)
  File "/opt/python3/lib/python3.10/statistics.py", line 328, in mean
    raise StatisticsError('mean requires at least one data point')
statistics.StatisticsError: mean requires at least one data point